on: push
  
jobs:
  maven_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3 # use to upload the repository content into the runner workspace: GITHUB_WORKSPACE
      - name: Setup Java environment
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'
      - name: Running tests 
        run: ./mvnw test
      - name: Upload testing results as artifacts
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: "Maven test results"
          path: "**/TEST-*.xml"
  
  maven_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build the project
        run: ./mvnw clean install -DskipTests
      - name: Archive build output
        uses: actions/upload-artifact@v2
        with:
          name: "Maven build output"
          path: "**/target/"
    
