on: push
  
jobs:
  maven_test:
    runs-on: ubuntu-latest
    container:
      image: java:8
    steps:
      - name: Checkout 
        uses: actions/checkout@v3 # use to upload the repository content into the runner workspace: GITHUB_WORKSPACE
      - name: Running tests 
        run: ./mvn test
      - name: Upload testing results as artifacts
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: "Maven test results"
          path: "**/TEST-*.xml"
  
  maven_build:
    runs-on: ubuntu-latest
    container:
      image: java:8
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      - name: Build the project
        run: ./mvnw build
      - name: Archive build output
        uses: actions/upload-artifact@v2
        with:
          name: "Maven build output"
          path: "**/target/"
    
